apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hitheshgowda10docker/chat-app:b7c76d6a1eb34f540f00446a498dd41931455d90
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: JWT_SECRET
          value: "chatappsecret"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/chat-app"
