sonar.projectKey=chat-app
sonar.projectName=chat-app
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src

sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/*.test.js

sonar.sourceEncoding=UTF-8
